### ISSUE TITLE
Templating inside variables

### ISSUE THREAD

**Issue by dwainscheeren** [custom-cards/button-card#294] opened 2020-03-14 21:37 UTC
Would it be possible to add templating to variables?

**Comment by dwainscheeren** [comment] 2020-03-14 21:45
Something like (example):
```YAML
header_states_door:
  show_state: true
  show_label: true
  name: Doors
  icon: mdi:door
  variables:
    test_one: >
      [[[
        var test = 'test';

        return test;
      ]]]
  label: '[[[ return variables.test_one ]]]'
  name: '[[[ return variables.test_one ]]]'
```

**Comment by RomRider** [comment] 2020-03-15 18:35
Duplicate of #281

**Closed** 2020-03-15 18:59 UTC
Labels: FR
