### ISSUE TITLE
Installation link returns 404

### ISSUE THREAD

**Issue by jayheavner** [custom-cards/button-card#243] opened 2019-11-04 13:57 UTC
Just FYI. The download link is referencing /dist which isn't in the repo. Simple enough to clone, install, and build but it might trip some folks up.

**Comment by RomRider** [comment] 2019-11-04 14:19
Thanks, I'll fix that. The file is in the release section of the repository no need to build it yourself.

**Comment by m90att** [comment] 2019-11-11 13:03
Tripped me up.  where can i get the .js file to install please?  I can't see a release section

**Comment by RomRider** [comment] 2019-11-11 22:27
Here: https://github.com/custom-cards/button-card/releases

**Comment by RomRider** [comment] 2020-01-03 18:16
Duplicate of #251

**Comment by RomRider** [comment] 2020-01-03 18:16
Fixed in 6dc0573cf7a5802da96c2c1b20009fd5f5e120e1

**Closed by RomRider** 2020-01-03 18:16 UTC
Labels: bug
