### ISSUE TITLE
allow lock to be set on Hold action

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#230] opened 2019-10-15 12:32 UTC
**Is your feature request related to a problem? Please describe.**

Someone accidentally taps a lock and taps it again...which is kind of easy

**Describe the solution you'd like**

For security reason, I would love to be able to 'lock' the hold-action, (and set tap-action to none or more-info) so that another layer of security's builtin.

**Describe alternatives you've considered**

**Additional context**

please see https://community.home-assistant.io/t/lovelace-button-card/65981/2545?u=mariusthvdb

and code I would suggest:

```
  - type: 'custom:button-card'
        template: button_default_title
        lock: true
        confirmation: Sure to toggle?
        tap_action:
          action: none
        hold_action:
          action: call-service
          service: homeassistant.toggle
          service_data:
            entity_id: group.philips_motion_sensor_switches_all
          haptic: success
```

thanks for considering

**Comment by RomRider** [comment] 2019-10-20 16:36
If I understand correctly, you want an option to unlock the card by holding the button instead of tapping on it?
Then the button would be unlocked and you could also achieve `tap_action`.

**Comment by RomRider** [comment] 2019-10-20 22:36
Seems like a duplicate of #220

**Comment by iantrich** [comment] 2019-10-21 02:35
FWIW I added this to the restriction-card after reading this FR
https://github.com/custom-cards/restriction-card/releases/tag/1.0.6

**Closed** 2019-10-21 08:24 UTC
Labels: FR, WIP
