### ISSUE TITLE
2023.1.0 broke entity state display in local language

### ISSUE THREAD

**Issue by Opontios** [custom-cards/button-card#646] opened 2023-01-05 17:02 UTC
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
After the 2023.1.0 update the display of the entity state in local language reverted to default (English)
**Version of the card**
Version: 3.5.0-dev.1

```


**Expected behavior**
To show the state in local language, as before

**Desktop (please complete the following information):**
 - Browser: all existing
 - Version: latest

**Comment by Xitro01** [comment] 2023-04-17 21:09
Same issue here, running v3.5.0 and HA 2023.4.4.
All my card state's went to "Off", "On", "Heat", etc. instead of showing them in Dutch.

Any news regarding this?

**Comment by MicheleMercuri** [comment] 2023-05-31 07:46
same issue.

**Comment by maradonaxsempre** [comment] 2023-06-27 08:22
Hi guys, any news about the status in English only?

**Comment by RomRider** [comment] 2023-07-26 00:18
This is fixed in the beta version. I'm closing in favor of #685

Duplicate of #685

**Closed by RomRider** 2023-07-26 00:18 UTC
Labels: bug

**Comment by zs2766** [comment] 2023-07-27 02:28
> This is fixed in the beta version. I'm closing in favor of #685
> 
> Duplicate of #685

May I ask when the official version will be released to address this issue?

**Comment by RomRider** [comment] 2023-07-27 06:46
By the end of this week

**Comment by zs2766** [comment] 2023-07-30 13:06
> By the end of this week

I have updated my home assistant to the latest version, and the "button card" has also been updated to the latest version 4.0. However, the physical status of the card still cannot be translated, and it still displays English instead of my native language

**Comment by Mariusthvdb** [comment] 2023-07-30 14:07
Did you apply the required config ?

**Comment by RomRider** [comment] 2023-07-30 14:24
It's probably a cache issue @zs2766, hard refresh multiple times or clear your cache.

**Comment by zs2766** [comment] 2023-08-01 03:37
> It's probably a cache issue @zs2766, hard refresh multiple times or clear your cache.

I have tried to clear the browser cache or log in on another computer, but the problem remains unresolved

**Comment by zs2766** [comment] 2023-08-02 03:51
> Did you apply the required config ?
> 
> Read the documentation , particularly on `helpers.localize()`

Hello, I did not participate in the 4.0 testing. I upgraded directly from 3.5 to the official version of 4.0
