### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by IIIdefconIII** [custom-cards/button-card#61] opened 2019-02-20 22:18 UTC
since 0.88
virt env
no traceback

http://10.3.1.2:8123/local/button-card.js?v=0.0.5:1:39 Uncaught TypeError: Cannot convert undefined or null to object

**Comment by PierpaoloPernici** [comment] 2019-02-21 13:06
check #57 and #62

**Comment by ammmze** [comment] 2019-02-23 03:41
Buttons should load (once you update your `button-card.js`) now that #63 has been merged

**Comment by bouwew** [comment] 2019-02-23 09:40
![image](https://user-images.githubusercontent.com/11290930/53284628-53da2b00-3757-11e9-8d4c-e69c2b09acec.png)

Do this and select

**Comment by artomka** [comment] 2019-02-23 14:13
After upgrading to the version 0.0.6 I still have the same error “Cannot convert undefined or null to object”.

**Comment by bouwew** [comment] 2019-02-23 14:43
I had the same issue, it is caused by your browser, see the solution for Chrome in my previous post.

**Comment by IIIdefconIII** [comment] 2019-02-23 22:39
saw alot of converstation this week, is the one on the main github now the latest?

**Comment by CrazYoshi** [comment] 2019-02-24 00:35
> I had the same issue, it is caused by your browser, see the solution for Chrome in my previous post.

I empty the cache and reload but I have the same error: "Uncaught TypeError: Cannot convert undefined or null to object"

**Comment by iantrich** [comment] 2019-04-17 23:11
Is this still an issue?

**Comment by bouwew** [comment] 2019-04-20 08:38
No, the provided solution works.

**Closed** 2019-04-20 12:47 UTC
Labels: bug, help wanted, waiting for reply
