### ISSUE TITLE
Entity State displays „raw“ Informations

### ISSUE THREAD

**Issue by mcfly2283** [custom-cards/button-card#685] opened 2023-04-13 16:48 UTC
With the latest Version of HA 2023.4.3 the State of a Person inside a Button-Card is displayed as state "home" and "not_home", not as usual with the corresponding German Translation "Zu Hause" or "Abwesend". Other Zones and other Native-Cards are right. 

Button-Card Version: [3.5.0] (2023-04-02) latest

In this case it seems there is a Problem related to Button-Card and not with HA.

Button-Card:
![image](https://user-images.githubusercontent.com/34608100/231828843-7f40ea29-7605-431f-a06a-dd10edfe58f6.png)

Native Card:
![image](https://user-images.githubusercontent.com/34608100/231830312-4cb39be7-01f3-414b-964d-a0a78a5963af.png)

Syntax:
      - type: custom:button-card
        entity: person.XXYY
        show_name: false
        show_state: true
        show_entity_picture: true
        styles:
          card:
            - font-size: 14px
            - padding: 10%
          icon:
            - width: 70px
            - height: 70px
            - padding: 0px 0px 0px 0px

**Comment by pejotigrek** [comment] 2023-04-14 09:14
it's affecting all entity domains. language translations are ignored in button-card in latest HA.
it just displays "raw" state of an entity:
![image](https://user-images.githubusercontent.com/10796588/232001579-eea97ad8-5a3a-4037-9ee1-10ae1e7823a4.png)

**Comment by pejotigrek** [comment] 2023-04-14 09:16
@mcfly2283 are you able to change the issue's topic? maybe "entity state displays raw information, not local/translated value" or something similar would be more fitting?

**Comment by Mariusthvdb** [comment] 2023-04-14 09:26
seems identical to https://github.com/benct/lovelace-multiple-entity-row/issues/292#issuecomment-1507232575

quoting Frontend dev Paul:

> With 2023.4, HA core added support for translations attributes and name so entity state translation keys have changed too.
> The computeStateDisplay in this repository is outdated and need to be updated with new translation keys.
> 
>

**Comment by mcfly2283** [comment] 2023-04-14 11:59
> @mcfly2283 are you able to change the issue's topic? maybe "entity state displays raw information, not local/translated value" or something similar would be more fitting?

I don‘t think so…

**Comment by mcfly2283** [comment] 2023-04-14 12:01
> @mcfly2283 are you able to change the issue's topic? maybe "entity state displays raw information, not local/translated value" or something similar would be more fitting?

Done 👍

**Comment by jjprz** [comment] 2023-04-14 22:11
same problem here but in spanish

**Comment by sheminasalam** [comment] 2023-04-15 15:45
same problem here with my door binary sensors.
![image](https://user-images.githubusercontent.com/45196177/232234982-aacdbb79-21d2-4f01-b43d-f5ea6b8b4b75.png)

**Comment by gabrymed** [comment] 2023-04-15 16:49
Same problem for me with my gas and fire binary sensors.
![Immagine](https://user-images.githubusercontent.com/57106603/232238925-5340f299-f5d3-4cc2-92a5-053f52f9421e.jpg)

**Comment by h4nnes** [comment] 2023-04-17 08:13
> I have a similar problem. After the update, on and off are now displayed and no longer the German designation. The same applies to windows/doors as on/off. In Home Assistant, however, it is correctly displayed as open/closed.

Same here

**Comment by Scoff123** [comment] 2023-04-17 08:27
Same with my Binary Sensors for windows and doors - previously they would show a 'state' of Open or Closed, but now they show the actual Binary state of On or Off

<img width="83" alt="image" src="https://user-images.githubusercontent.com/96984460/232427606-d27afe43-4e4f-4f7f-9f04-0ddbb7ba20b9.png">

<img width="467" alt="image" src="https://user-images.githubusercontent.com/96984460/232428270-8b5dc885-1cc4-468f-89a0-5a145c9a88fc.png">

```
Garage Door Sensor contact (binary_sensor.garage_door_sensor_contact)
MQTT discovery data:
Topic: homeassistant/binary_sensor/0x00158d00090ee999/contact/config
Payload
availability:
  - topic: zigbee2mqtt/bridge/state
    value_template: '{{ value_json.state }}'
  - topic: zigbee2mqtt/Garage Door Sensor/availability
    value_template: '{{ value_json.state }}'
availability_mode: all
device:
  identifiers:
    - zigbee2mqtt_0x00158d00090ee999
  manufacturer: Xiaomi
  model: Aqara door & window contact sensor (MCCGQ11LM)
  name: Garage Door Sensor
  sw_version: 3000-0001
device_class: door
name: Garage Door Sensor contact
payload_off: true
payload_on: false
state_topic: zigbee2mqtt/Garage Door Sensor
unique_id: 0x00158d00090ee999_contact_zigbee2mqtt
value_template: '{{ value_json.contact }}'
platform: mqtt
```

**Comment by micium** [comment] 2023-04-19 10:21
Hi all,
waiting for an updated version that solves the problem, is it possible to apply a workaround?

Kind Regards

**Comment by mcfly2283** [comment] 2023-04-19 11:34
> Hi all, waiting for an updated version that solves the problem, is it possible to apply a workaround?
> 
> Kind Regards

I don‘t think there is a workarounds. This issue is related to every 3rd Party Card. It is a bit courios that there was no breaking change for the devs before…

**Comment by jensrossbach** [comment] 2023-04-19 11:51
You could use state_display as workaround.

**Comment by FieserOstfriese** [comment] 2023-04-25 12:14
So I can't get it with the state_display somehow. No matter how I embed it, it doesn't work. There won't be an update anymore because the button card is no longer maintained, right? Maybe someone has a code example how to include state_display exactly?

**Comment by Mariusthvdb** [comment] 2023-04-25 12:18
what are you trying to do? we cant help you if you dont give us anything.
btw, this is better suited for the Community, as there is no 'bug' here, and config questions shouldnt be littering these repo issues.

**Comment by FieserOstfriese** [comment] 2023-04-25 12:36
> what are you trying to do? we cant help you if you dont give us anything. btw, this is better suited for the Community, as there is no 'bug' here, and config questions shouldnt be littering these repo issues.
> 
> state_display is really easy btw. just set a value to display, (template or not) and also use the `show_state: true` option of course.

I've tried everything. It just doesn't work. Only on or off is displayed. I think I'm just too stupid for that *g*


```
type: custom:button-card
template: container
name: Fenster & Türen
custom_fields:
  buttons:
    card:
      type: horizontal-stack
      cards:
        - entity: binary_sensor.fenster_kuche_contact
          label: Küche
          name: Küche
          icon: mdi:window-closed-variant
          show_state: true
          state_color: true
          show_name: false
          show_label: true
          device_class: window
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.fenster_kinderzimmer_contact
          label: Kinderzimmer
          name: Kinderzimmer
          icon: mdi:window-closed-variant
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.fenster_schlafzimmer_contact
          label: Schlafzimmer
          icon: mdi:window-closed-variant
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.badezimmerfenster_contact
          label: Badezimmer
          icon: mdi:window-closed-variant
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.garagentur_contact
          label: Garagentür
          icon: mdi:door-closed
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.haustur_contact
          label: Haustür
          icon: mdi:door-closed
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.terassentur_contact
          label: Terassentür
          icon: mdi:door-closed
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.garagentor_contact
          label: Garagentor
          icon: mdi:garage
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
```

**Comment by Mariusthvdb** [comment] 2023-04-25 13:22
uhm.... you dont have state_display set at all?

**Comment by pejotigrek** [comment] 2023-04-28 16:20
you think? I don't see it as just "my opinion" :)
this is clearly an issue - I am not telling "me good, button-card bad" [because button-card is one of the best additions to the HA that I'm using], but this [probably] is caused by some changes in the HA, so using `state_display` is just a quick workaround, not the desired "go-to" setting. as far as it is a good fix [no matter if I'll use it or not] it is just a way of dealing with something that [I hope] will be eventually fixed in the card's code itself. I am not ranting or something, I am just wishing to keep this issue open, so with a dash of good luck we'll see states working correctly in near or at least not so far future ;)

believe me, if I'd know a bit about developing cards/extensions/integrations, I'd be more than happy to prepare pull request and fix it. but sadly I am total noob in terms of dealing with python, or programming at all ;(

**Comment by pejotigrek** [comment] 2023-04-29 00:03
> Well, state_display is capable of way more than fixing this, so it is hardly a hack, but has been a long standing main feature.

OMG. dude, this is a hack in THIS particular situation!
we all know this is a normal, legit, main feature of the button-card! I use it on a daily basis in some other scenarios.
but in case of wrongly displayed translations, caused by HA modification - this is a hack to fix the issue.

> Meanwhile, adapt your cards. On the positive side: you won't be forced to use the sometimes silly official lokalizations...

this is plainly a joke, right?
it's not up to you to judge the localizations I, or others from above comments, want to use.. if yours are silly, well, I feel bad for you. but please don't try to push your agenda to us all.

**Comment by ildar170975** [comment] 2023-05-03 12:32
Test this:
https://github.com/custom-cards/button-card/pull/692

**Comment by Mariusthvdb** [comment] 2023-07-23 20:40
HI Rom,

thanks for updating, many issues have been resolved, also those state translations (binary_sensor motion now no longer show on/off ;-)

Now you're back, please let m quickly followup with this
 I still see eg this 'rainy':

<img width="135" alt="Scherm­afbeelding 2023-07-23 om 22 35 16" src="https://github.com/custom-cards/button-card/assets/33354141/1d30f313-f016-47e1-b7f9-38b8c8efa808">

while it should translate to Regenachtig:

<img width="573" alt="Scherm­afbeelding 2023-07-23 om 22 34 58" src="https://github.com/custom-cards/button-card/assets/33354141/9877cf87-615c-46ec-b551-249bd29207bc">


confg:

```
type: custom:button-card
template:
  - styles_cf_notification
  - styles_cf_notification_left
show_entity_picture: true
entity_picture: >
  [[[ return states['sensor.weather_animated_icon'].attributes.entity_picture; ]]]
show_state: true
show_name: false
size: 100%
aspect_ratio: 1
show_icon: false
entity: sensor.buienradar_condition
```

please have another look at that?

**Comment by RomRider** [comment] 2023-07-23 21:43
@Mariusthvdb, I'm about to release a new version with support for new actions that should also fix this translation issue.

**Comment by Mariusthvdb** [comment] 2023-07-24 05:58
> @Mariusthvdb, I'm about to release a new version with support for new actions that should also fix this translation issue.

confirmed:

<img width="430" alt="Scherm­afbeelding 2023-07-24 om 07 55 32" src="https://github.com/custom-cards/button-card/assets/33354141/cc41f813-3985-456a-b997-87778cd16b32">

great.

Btw, for this specific integration (entity): why wouldn't this show the set entity_picture. this is a buienradar entity, and the integration sets an entity_picture as you can see in the screenshot above. Currently it is Cloudy (translates to Bewolkt), ent the entity_picture shows as:

<img width="573" alt="Scherm­afbeelding 2023-07-24 om 07 57 56" src="https://github.com/custom-cards/button-card/assets/33354141/66d5653c-e02d-4487-aa02-fc56c508fa29">

**Comment by Mariusthvdb** [comment] 2023-07-24 08:46
getting back to this... sorry

I am using many buttons that have a template with 
```
  custom_fields:
    notification: >
      [[[ return entity.state; ]]]
```

these are not translated and get the 'raw' are state:

<img width="254" alt="Scherm­afbeelding 2023-07-24 om 10 39 11" src="https://github.com/custom-cards/button-card/assets/33354141/c9c45597-ce03-4a2c-899c-9f287b395fd5">

note that in this screen, also the name of the right button gets `Cover: closed` because of its template in state_display:

```
state_display: >
  [[[ return 'Cover: ' + entity.state; ]]]
```

please see if this is expected, or, maybe still needs enhancement so we can see these templates translated correctly too?

**Comment by RomRider** [comment] 2023-07-24 10:56
This translation will be possible in the next beta release. I just commited the code for that @Mariusthvdb

**Comment by Mariusthvdb** [comment] 2023-07-24 11:45
just installed b6, but still those entity templates use the raw value, was this supposed to have changed with that?

**Comment by RomRider** [comment] 2023-07-24 11:49
Yes, check the documentation, you need to use a function.

- `localize(entity, state?)`: a function which localizes a state (eg. `localize(entity)`) and returns a string. Takes an entity object as argument (not the state of the entity as we need context) and takes an optional `state` string as argument. If `state` is not provided, it localizes the state of the `entity` (Eg. `localize(entity)` or `localize(states['weather.your_city'])`). If `state` is provided, it localizes `state` in the context of the `entity` (eg. : `localize(states['weather.your_city'], states['weather.your_city'].attributes.forecast[0].condition)`)

**Comment by Mariusthvdb** [comment] 2023-07-24 14:08
Jerome,

on localizing attributes, might be cool to also add the to the documentation, on translating local 'entity' attributes
```
  [[[ return localize( entity, entity.attributes.forecast[0].condition) ); ]]]

```

in addition to what you copied above on localizing..

**Comment by RomRider** [comment] 2023-07-24 14:09
It's in the example of the documentation, am I wrong? : `localize(states['weather.your_city'], states['weather.your_city'].attributes.forecast[0].condition)`

**Comment by Mariusthvdb** [comment] 2023-07-24 14:12
no not wrong.... it took me a while to figure out this (using an external entity) 

```
[[[ return localize(states['weather.your_city'], states['weather.your_city'].attributes.forecast[0].condition); ]]]
```
would work likewise for a local entity

```
[[[ return localize( entity, entity.attributes.forecast[0].condition ); ]]]
```

just believe it would help prevent questions ;-)

**Comment by Mariusthvdb** [comment] 2023-07-24 14:32
> EDIT: Oh I see what you mean, about 'local' entity. The entity of the card itself... I'll add an example

exactly that yes. Might me be, but since I learned the hard way that [templating those global variables hurts the UI performance much more than local variables](https://github.com/Mariusthvdb/custom-ui/blob/master/EXAMPLES.md#available-variables), my eye is just focussed on it, and I try to prevent it as much a possible.

Not sure if from your perspective this still holds ( I mean, the warning was written in a completely different stage of HA development, actually still using the states frontend....) but still, can hurt to be aware.

**Closed** 2023-07-29 00:11 UTC
Labels: bug, released on @beta
