### ISSUE TITLE
Show the timestamp as HomeAssistant does

### ISSUE THREAD

**Issue by Danit2** [custom-cards/button-card#666] opened 2023-03-18 11:49 UTC
Is it possible to show the timestamp as text like in HomeAssistant?

I would like to show a timestamt as `label` but in the same format as HomeAssistant does.

Like: `2 minutes ago` or `in 5 minutes`

Is this possible?
Can someone show me a example? 

Thanks.

**Comment by Mariusthvdb** [comment] 2023-04-20 11:17
join and search the community, there are plenty examples of javascript templates doing this.

or use the label and `show_last_changed: true` on this card, it is built in by default

<img width="247" alt="Scherm­afbeelding 2023-04-20 om 13 17 04" src="https://user-images.githubusercontent.com/33354141/233350406-705705b9-b026-4985-b68f-9f633a9ab9dc.png">

**Comment by RomRider** [comment] 2023-07-26 00:29
Supported in 4.0.0-dev11 and future 4.0.0 in any template.

Duplicate of #701 
Closing

**Closed by RomRider** 2023-07-26 00:29 UTC
Labels: bug
