### ISSUE TITLE
Cannot read property 'states' of undefined.

### ISSUE THREAD

**Issue by dwainscheeren** [custom-cards/button-card#337] opened 2020-06-01 08:50 UTC
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
Sometimes when I enter a page I get the following error `button-card.js:1638 Uncaught (in promise) TypeError: Cannot read property 'states' of undefined`
It happens on this part:  `this._stateObj = this._config.entity ? this._hass.states[this._config.entity] : void 0;try {` When I then keep that page open for some minutes some of the button cards suddenly starts working and show up (otherwise they are just empty/not visible).

**Version of the card**
Version:  3.3.5

**To Reproduce**
It happens in different ways I use button card but an example is:
```yaml
- type: custom:auto-entities
            filter:
              exclude:
                - entity_id: '*battery_state*'
              include:
                - entity_id: '*battery*'
                  domain: sensor
                  options:
                    type: custom:button-card
                    template: house_data_item
                    entity: this.entity_id
                    icon: >
                      [[[ 
                        if (states[`this.entity_id`].state == 'unknown'){
                          return 'mdi:battery-alert';
                        } else {
                          return 'mdi:battery';
                        }
                      ]]]
                - type: custom:button-card
                  color_type: blank-card
                  aspect_ratio: 1/1
```

**Desktop (please complete the following information):**
Latest version chrome

**Comment by dwainscheeren** [comment] 2020-06-01 08:55
This also started happening from HA 0.110

**Comment by dwainscheeren** [comment] 2020-06-02 11:26
![](http://puu.sh/FRLDF/351f7ff826.png)

**Comment by RomRider** [comment] 2020-06-02 11:28
Will fix that soon. They've changed something in core which make the hass object undefined while the card is created and it fucks everything up...

**Comment by thomasloven** [comment] 2020-06-02 11:45
You can never trust the order `setConfig`, `set hass` or attachment to DOM will happen in. Especially not when the editor is involved. Also, `setConfig` may be called hundreds of times during the lifetime of the card - just a heads up.

**Comment by RomRider** [comment] 2020-06-02 12:34
I understand, however it used to be always the case in the past and the latest release broke a lot of of cards because of that. So I see that as a breaking (big) change :)

**Comment by thomasloven** [comment] 2020-06-02 13:12
Well, it used to be *close enough* to always... but i agree, it's an unfortunate change that could have been communicated more clearly.

**Comment by RomRider** [comment] 2020-06-02 15:59
I'm just wondering something then... How do you tackle the attachement to DOM when you need `hass` to be available in the `connectedCallback` and it is not?
I really hate any solution involving `setTimeout` to retry later...

**Comment by thomasloven** [comment] 2020-06-02 19:07
If it's really necessary and can't be fixed by restructuring, a flag could help.

```javascript

initial_setup() {
  if(this.hass === undefined) return;
  if(this._config === undefined) return;
  if(!this.isConnected) return;
  this.initial_setup_complete = true;
  ... do setup stuff ...
}

setConfig(config) {
  ... do stuff ...
  this._config = config;
  if(this.initial_setup_complete === undefined) {
    this.initial_setup();
  }
}

set hass(hass) {
  ... do stuff ...
  if(this.initial_setup_complete === undefined) {
    this.initial_setup();
  }
}

connectedCallback() {
  ... you get the point ...
}
```

**Comment by dwainscheeren** [comment] 2020-06-05 09:44
Any news on this @RomRider :)

**Comment by RomRider** [comment] 2020-06-05 09:46
Will work on it over the weekend, didn't have time lately, sorry :/

**Comment by parautenbach** [comment] 2020-06-06 02:50
Here is another case to test or help reproduce this. I get the reported error using a timer:

```
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: timer.lhs_garage_door_timer
```

**Closed** 2020-06-07 17:42 UTC
Labels: bug

**Comment by RomRider** [comment] 2020-06-07 17:46
@dwainscheeren, please give 3.3.6 a go an report back :)

**Comment by RomRider** [comment] 2020-06-07 18:02
@parautenbach, the timer issue should also be fixed btw ;)

**Comment by dwainscheeren** [comment] 2020-06-07 18:28
Tested it for some minutes, until now no errors. So seems to be fixed. :) I report back here if not. Thanks!

**Comment by parautenbach** [comment] 2020-06-07 19:54
Thanks a mil for the quick release! I downloaded and installed the update and haven't seen the issue. I'll let you know should it appear again.
